relatorio_etiqueta_alunos:
  radio_itens:
    1:
      table_name: aluno
      filted_columns:
        nome:
          id: nome
          nome: nome
          type: text
          editable: 0
        endereco:
          id: endereco
          nome: endereco
          type: text
          editable: 0
        bairro/cidade:
          id: bairro/cidade
          nome: bairro/cidade
          type: text
          editable: 0
#        cidade:
#          id: cidade
#          nome: cidade
#          type: text
#          editable: 0
        uf/cep:
          id: uf/cep
          nome: uf/cep
          type: text
          editable: 0
#        cep:
#          id: cep
#          nome: cep
#          type: text
#          editable: 0
      default_columns:
        - nome
        - endereco
        - bairro/cidade
        - uf/cep
#        - n_irmaos
#        - responsavel_financeiro
#        - tel_responsavel_financeiro
    2:
      table_name: turma_aluno
      filted_columns:
        id_turma:
          id: id_turma
          nome: id_turma
          type: numeric
          editable: 0
        status_turma:
          id: status_turma
          nome: status_turma
          type: text
          editable: 0
        nivel:
          id: nivel
          nome: nivel
          type: text
          editable: 0
        inicio_turma:
          id: inicio_turma
          nome: inicio
          type: text
          editable: 0
        fim_turma:
          id: fim_turma
          nome: fim
          type: text
          editable: 0
        map:
          id: map
          nome: map
          type: text
          editable: 0
        idioma:
          id: idioma
          nome: idioma
          type: text
          editable: 0
        id_aluno:
          id: id_aluno
          nome: id_aluno
          type: numeric
          editable: 0
        nome:
          id: nome
          nome: nome
          type: text
          editable: 0
        status_aluno:
          id: status_aluno
          nome: status aluno
          type: text
          editable: 0
        dat_nasc:
          id: dat_nasc
          nome: dat_nasc
          type: text
          editable: 0
        inicio_aluno:
          id: inicio_aluno
          nome: inicio
          type: text
          editable: 0
        responsavel_financeiro:
          id: responsavel_financeiro
          nome: resp. financ
          type: text
          editable: 0
        tel_responsavel_financeiro:
          id: tel_responsavel_financeiro
          nome: tel resp. financ
          type: text
          editable: 0
      default_columns:
        - id_turma
        - status_turma
        - nivel
        - inicio_turma
        - fim_turma
#        - map
        - idioma
#        - id_aluno
        - nome
        - status_aluno
#        - dat_nasc
#        - inicio_aluno
        - responsavel_financeiro
        - tel_responsavel_financeiro