home:

  fig_aluno:
    hovermode: x unified
#    height: 600
    template: plotly_white
#    separators: ',.'
#    showlegend: True
    margin:
      l: 20
      r: 25
      t: 5
      b: 0

    yaxis:
      side: right
      tickmode: auto

    showlegend: True

    legend:
      orientation: h
      yanchor: bottom
      xanchor: right
      x: 1
      y: -0.25

  fig_format:
    hovermode: x unified
    height: 600
    template: plotly_white
    separators: ',.'
    showlegend: True

    yaxis:
      side: left

    yaxis2:
      side: right
      overlaying: y
      tickmode: auto

    legend:
      orientation: h
      yanchor: bottom
      xanchor: right
      x: 1
      y: -0.25

  graph:
    locale: pt
    showLink: False
    displaylogo: False
    responsive: True

